tasks:
- install:
- ceph:
- rgw: [client.0]
- s3tests:
    client.0:
      unit_test_scan: True
      rgw_server: client.0
overrides:
  ceph:
    conf:
      client:
        rgw lc debug interval: 10
