{
 "title": "Ceph NVMe-oF Gateways - Performance 2",
 "description": "Ceph NVMe-oF gateways overview",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "group",
    "label": "Gateway Group",
    "query": "label_values(ceph_nvmeof_gateway_info,group)"
   },
   {
    "name": "gateway",
    "label": "Gateway Hostname",
    "query": "label_values(ceph_nvmeof_gateway_info{group=~'$group'},hostname)"
   },
   {
    "name": "subsystem",
    "label": "Subsystem NQN",
    "query": "label_values(ceph_nvmeof_subsystem_metadata{group=~'$group'},nqn)"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "AVG Reactor CPU Usage by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(instance) (rate(ceph_nvmeof_reactor_seconds_total{mode=\"busy\",instance=~\"$gateway\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reactor Threads CPU Usage : $gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(ceph_nvmeof_reactor_seconds_total{mode=\"busy\", instance=~\"$gateway.*\"}[1m]))\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "AVG I/O Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg((rate(ceph_nvmeof_bdev_read_seconds_total{instance=~\"$gateway\"}[30s]) / rate(ceph_nvmeof_bdev_reads_completed_total{instance=~\"$gateway\"}[30s])) > 0)\n",
     "legendFormat": "Reads"
    },
    {
     "expr": "avg((rate(ceph_nvmeof_bdev_write_seconds_total{instance=~\"$gateway\"}[30s]) / rate(ceph_nvmeof_bdev_writes_completed_total{instance=~\"$gateway\"}[30s])) > 0)",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "IOPS by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(ceph_nvmeof_bdev_reads_completed_total{instance=~\"$gateway\"}[1m]) + rate(ceph_nvmeof_bdev_writes_completed_total{instance=~\"$gateway\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IOPS by NVMe-oF Subsystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "\nsum by(nqn) ((rate(ceph_nvmeof_bdev_reads_completed_total{instance=~\"$gateway\"}[1m]) + rate(ceph_nvmeof_bdev_writes_completed_total{instance=~\"$gateway\"}[1m])) * on(instance,bdev_name) group_right ceph_nvmeof_subsystem_namespace_metadata{instance=~\"$gateway\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOP 5 - IOPS by device for '$subsystem'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "topk(5, (sum by(pool_name, rbd_name) (((rate(ceph_nvmeof_bdev_reads_completed_total{instance=~\"$gateway\"}[1m]) + rate(ceph_nvmeof_bdev_writes_completed_total{instance=~\"$gateway\"}[1m])) * on(instance,bdev_name) group_right ceph_nvmeof_bdev_metadata{instance=~\"$gateway\"}) * on(instance, bdev_name) group_left(nqn) ceph_nvmeof_subsystem_namespace_metadata{nqn=~\"$subsystem\",instance=~\"$gateway\"})))",
     "legendFormat": "{{pool_name}}/{{rbd_name}}"
    }
   ]
  },
  {
   "title": "Throughput by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(ceph_nvmeof_bdev_read_bytes_total{instance=~\"$gateway\"}[1m]) + rate(ceph_nvmeof_bdev_written_bytes_total{instance=~\"$gateway\"}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Throughput by NVMe-oF Subsystem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "\nsum by(nqn) ((rate(ceph_nvmeof_bdev_read_bytes_total{instance=~\"$gateway\"}[1m]) + rate(ceph_nvmeof_bdev_written_bytes_total{instance=~\"$gateway\"}[1m])) * on(instance,bdev_name) group_right ceph_nvmeof_subsystem_namespace_metadata{instance=~\"$gateway\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TOP 5 - Throughput by device for '$subsystem'",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(5, (sum by(pool_name, rbd_name) (((rate(ceph_nvmeof_bdev_read_bytes_total{instance=~\"$gateway\"}[1m]) + rate(ceph_nvmeof_bdev_written_bytes_total{instance=~\"$gateway\"}[1m])) * on(instance,bdev_name) group_right ceph_nvmeof_bdev_metadata{instance=~\"$gateway\"}) * on(instance, bdev_name) group_left(nqn) ceph_nvmeof_subsystem_namespace_metadata{nqn=~\"$subsystem\",instance=~\"$gateway\"})))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}