{
 "title": "Ceph NVMe-oF Gateways - Performance by Gateway",
 "description": "Ceph NVMe-oF gateways overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "group",
    "label": "Gateway Group",
    "query": "label_values(ceph_nvmeof_gateway_info,group)"
   },
   {
    "name": "gateway",
    "label": "Gateway Hostname",
    "query": "label_values(ceph_nvmeof_gateway_info{group=~'$group'},hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance by Gateways - $group group/s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "AVG Reactor CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by(instance) (rate(ceph_nvmeof_reactor_seconds_total{mode='busy',instance=~'$gateway'}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Reactor Threads CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(ceph_nvmeof_reactor_seconds_total{mode='busy', instance=~'$gateway.*'}[1m]))\n",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "AVG I/O Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg((rate(ceph_nvmeof_bdev_read_seconds_total{instance=~'$gateway'}[30s]) / rate(ceph_nvmeof_bdev_reads_completed_total{instance=~'$gateway'}[30s])) > 0)\n",
     "legendFormat": "Reads"
    },
    {
     "expr": "avg((rate(ceph_nvmeof_bdev_write_seconds_total{instance=~'$gateway'}[30s]) / rate(ceph_nvmeof_bdev_writes_completed_total{instance=~'$gateway'}[30s])) > 0)",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Read IOPS by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(ceph_nvmeof_bdev_reads_completed_total{instance=~'$gateway'}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write IOPS by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(ceph_nvmeof_bdev_writes_completed_total{instance=~'$gateway'}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput by Gateway",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(ceph_nvmeof_bdev_read_bytes_total{instance=~'$gateway'}[1m]) + rate(ceph_nvmeof_bdev_written_bytes_total{instance=~'$gateway'}[1m]))",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}