{
 "title": "Ceph NVMe-oF Gateways - Performance by Subsystem",
 "description": "Ceph NVMe-oF gateways overview",
 "tags": [ "ceph-mixin" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(ceph_health_status, cluster)"
   },
   {
    "name": "subsystem",
    "label": "Subsystem NQN",
    "query": "label_values(ceph_nvmeof_subsystem_metadata,nqn)"
   }
  ]
 },
 "panels": [
  {
   "title": "Performance by Subsystem - $subsystem",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Read IOPS by NVMe-oF Subsystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(nqn) ((rate(ceph_nvmeof_bdev_reads_completed_total[1m])) * on(instance,bdev_name) group_right ceph_nvmeof_subsystem_namespace_metadata{nqn=~'$subsystem'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Write IOPS by NVMe-oF Subsystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(nqn) (rate(ceph_nvmeof_bdev_writes_completed_total[1m]) * on(instance,bdev_name) group_right ceph_nvmeof_subsystem_namespace_metadata{nqn=~'$subsystem'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Throughput by NVMe-oF Subsystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(nqn) ((rate(ceph_nvmeof_bdev_read_bytes_total[1m]) + rate(ceph_nvmeof_bdev_written_bytes_total[1m])) * on(instance,bdev_name) group_right ceph_nvmeof_subsystem_namespace_metadata{nqn=~'$subsystem'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Performance by namespaces of ($subsystem) subsystem/s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Reads IOPS by device for $subsystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(pool_name, rbd_name, nsid, nqn) (rate(ceph_nvmeof_bdev_reads_completed_total[1m]) * on(instance, bdev_name) group_left(nqn, nsid) ceph_nvmeof_subsystem_namespace_metadata{nqn=~'$subsystem'})",
     "legendFormat": "{{nqn}} - {{nsid}}"
    }
   ]
  },
  {
   "title": "Writre IOPS by device for $subsystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by(pool_name, rbd_name, nsid, nqn) (rate(ceph_nvmeof_bdev_writes_completed_total[1m]) * on(instance, bdev_name) group_left(nqn, nsid) ceph_nvmeof_subsystem_namespace_metadata{nqn=~'$subsystem'})",
     "legendFormat": "{{nqn}} (nsid: {{nsid}})"
    }
   ]
  },
  {
   "title": "Throughput by device for $subsystem",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(pool_name, rbd_name, nqn, nsid) ((rate(ceph_nvmeof_bdev_read_bytes_total[1m]) + rate(ceph_nvmeof_bdev_written_bytes_total[1m])) * on(instance, bdev_name) group_left(nqn, nsid) ceph_nvmeof_subsystem_namespace_metadata{nqn=~'$subsystem'})",
     "legendFormat": "{{nqn}} - {{nsid}}"
    }
   ]
  }
 ]
}